"""Public artifact-contract surface with no engine dependencies.

Application engines should import artifact types and contracts here (or from
the cohesive public submodules) rather than through the legacy
``commcanary.schema`` compatibility facade.
"""

from .canary import (
    ASSURANCE_STATES,
    CANARY_HASH_FIELD_NAMES,
    FIDELITY_ERROR_FIELDS,
    CanaryExpansionCounts,
    canary_artifact_provenance_sha256,
    canary_calibration_sha256,
    canary_execution_sha256,
    canary_scheduler_execution_sha256,
    iter_canary_logical_events,
    iter_canary_stored_leaf_events,
    preflight_canary_expansion,
    validate_canary,
)
from .comparison import comparison_policy_evaluations, derive_comparison_verdict, validate_comparison
from .io import (
    PARAM_TRACE_POLICY,
    SENSITIVE_JSON_POLICY,
    SHAREABLE_HTML_POLICY,
    AtomicWritePolicy,
    SymlinkPolicy,
    TempPlacement,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
)
from .json_codec import canonical_json_bytes, formatted_json_bytes
from .qualification import (
    QUALIFICATION_ARTIFACT_FORMATS,
    QUALIFICATION_ARTIFACT_FORMATS_V1,
    QUALIFICATION_ARTIFACT_PATHS,
    QUALIFICATION_ARTIFACT_PATHS_V1,
    QUALIFICATION_COMPUTE_RECIPE_METHOD,
    QUALIFICATION_COMPUTE_RECIPE_PROJECTION,
    QUALIFICATION_EXECUTION_ADAPTER,
    QUALIFICATION_EXECUTOR_CONTRACT,
    QUALIFICATION_PROGRAM_ENCODING,
    QUALIFICATION_REQUEST_FILENAME,
    QUALIFICATION_UPSTREAM_PARAM_COMPATIBILITY,
    qualification_request_sha256,
    validate_qualification_request,
)
from .qualification_decision import (
    QUALIFICATION_REASON_CODES,
    QUALIFICATION_VERDICTS,
    qualification_observation_sha256,
    qualification_policy_sha256,
    qualification_verdict_sha256,
    validate_qualification_observation,
    validate_qualification_policy,
    validate_qualification_verdict,
)
from .qualification_materialization import (
    QUALIFICATION_MATERIALIZATION_FILENAME,
    QUALIFICATION_REPLAY_PROGRAM_FILENAME,
    qualification_materialization_sha256,
    validate_qualification_materialization,
)
from .report import validate_report
from .schemas import load_schema_bytes
from .trace import validate_trace
from .wire import (
    MAX_ABS_INTEGER,
    MAX_RANK_COUNT,
    MAX_TIME_US,
    PROTOCOL_FINGERPRINT_EXCLUDE,
    SUPPORTED_OPS,
    JsonDict,
    arrival_skew_us,
    as_float,
    as_int,
    average_wait_us,
    clean_private_keys,
    load_json,
    load_json_document,
    merge_metadata,
    normalize_arrival_offsets,
    normalize_ranks,
    replay_protocol_sha256,
    require_format,
    write_json,
)

__all__ = [
    "ASSURANCE_STATES",
    "AtomicWritePolicy",
    "CANARY_HASH_FIELD_NAMES",
    "CanaryExpansionCounts",
    "FIDELITY_ERROR_FIELDS",
    "JsonDict",
    "MAX_ABS_INTEGER",
    "MAX_RANK_COUNT",
    "MAX_TIME_US",
    "PARAM_TRACE_POLICY",
    "PROTOCOL_FINGERPRINT_EXCLUDE",
    "QUALIFICATION_ARTIFACT_FORMATS",
    "QUALIFICATION_ARTIFACT_FORMATS_V1",
    "QUALIFICATION_ARTIFACT_PATHS",
    "QUALIFICATION_ARTIFACT_PATHS_V1",
    "QUALIFICATION_COMPUTE_RECIPE_METHOD",
    "QUALIFICATION_COMPUTE_RECIPE_PROJECTION",
    "QUALIFICATION_EXECUTION_ADAPTER",
    "QUALIFICATION_EXECUTOR_CONTRACT",
    "QUALIFICATION_MATERIALIZATION_FILENAME",
    "QUALIFICATION_PROGRAM_ENCODING",
    "QUALIFICATION_REPLAY_PROGRAM_FILENAME",
    "QUALIFICATION_REASON_CODES",
    "QUALIFICATION_REQUEST_FILENAME",
    "QUALIFICATION_UPSTREAM_PARAM_COMPATIBILITY",
    "QUALIFICATION_VERDICTS",
    "SENSITIVE_JSON_POLICY",
    "SHAREABLE_HTML_POLICY",
    "SUPPORTED_OPS",
    "SymlinkPolicy",
    "TempPlacement",
    "arrival_skew_us",
    "as_float",
    "as_int",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "average_wait_us",
    "canary_artifact_provenance_sha256",
    "canary_calibration_sha256",
    "canary_execution_sha256",
    "canary_scheduler_execution_sha256",
    "canonical_json_bytes",
    "clean_private_keys",
    "comparison_policy_evaluations",
    "derive_comparison_verdict",
    "formatted_json_bytes",
    "iter_canary_logical_events",
    "iter_canary_stored_leaf_events",
    "load_json",
    "load_json_document",
    "load_schema_bytes",
    "merge_metadata",
    "normalize_arrival_offsets",
    "normalize_ranks",
    "preflight_canary_expansion",
    "qualification_request_sha256",
    "qualification_materialization_sha256",
    "qualification_observation_sha256",
    "qualification_policy_sha256",
    "replay_protocol_sha256",
    "qualification_verdict_sha256",
    "require_format",
    "validate_canary",
    "validate_comparison",
    "validate_report",
    "validate_qualification_request",
    "validate_qualification_materialization",
    "validate_qualification_observation",
    "validate_qualification_policy",
    "validate_trace",
    "validate_qualification_verdict",
    "write_json",
]
