"""Stable process exit-code taxonomy."""

EXIT_SUCCESS = 0
EXIT_NEGATIVE_RESULT = 1
EXIT_USAGE = 2
EXIT_APPLICATION_ERROR = 3
EXIT_CHILD_FAILURE = 4
EXIT_INTERRUPTED = 130

__all__ = [
    "EXIT_APPLICATION_ERROR",
    "EXIT_CHILD_FAILURE",
    "EXIT_INTERRUPTED",
    "EXIT_NEGATIVE_RESULT",
    "EXIT_SUCCESS",
    "EXIT_USAGE",
]
